"""add revoked_at to tenant_invites

Revision ID: 9447c5d67e7b
Revises: fc71fc6cb340
Create Date: 2026-08-27 18:05:01.650237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9447c5d67e7b'
down_revision: Union[str, Sequence[str], None] = 'fc71fc6cb340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_invites', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_invites', 'revoked_at')
    # ### end Alembic commands ###
