"""add active and deleted to tenants table

Revision ID: b397094127ac
Revises: f8819ebd70e6
Create Date: 2026-08-27 14:05:38.846510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b397094127ac'
down_revision: Union[str, Sequence[str], None] = 'f8819ebd70e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('tenants', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'deleted')
    op.drop_column('tenants', 'active')
    # ### end Alembic commands ###
