"""create subject_class_enrollments table

Revision ID: c64f27978b95
Revises: e9453b2d65b1
Create Date: 2026-08-31 09:24:50.206592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64f27978b95'
down_revision: Union[str, Sequence[str], None] = 'e9453b2d65b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_class_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_class_id', sa.UUID(), nullable=False),
    sa.Column('tenant_member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'dropped', name='enrollment_status'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_class_id'], ['subject_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_member_id'], ['tenant_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_enrollment_active', 'subject_class_enrollments', ['subject_class_id', 'tenant_member_id'], unique=True, postgresql_where=sa.text('deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_enrollment_active', table_name='subject_class_enrollments', postgresql_where=sa.text('deleted = false'))
    op.drop_table('subject_class_enrollments')
    # ### end Alembic commands ###
