"""add deleted to rooms table

Revision ID: c852f1a96b2c
Revises: 9c5e87682219
Create Date: 2026-08-28 09:23:36.093968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c852f1a96b2c'
down_revision: Union[str, Sequence[str], None] = '9c5e87682219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_index(op.f('ix_rooms_tenant_id'), table_name='rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rooms_tenant_id'), 'rooms', ['tenant_id'], unique=False)
    op.drop_column('rooms', 'deleted')
    # ### end Alembic commands ###
