"""update subject_classes professor_id to reference tenant_members

Revision ID: e9453b2d65b1
Revises: 8c3439a483c1
Create Date: 2026-08-28 17:55:42.083755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9453b2d65b1'
down_revision: Union[str, Sequence[str], None] = '8c3439a483c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subject_classes_professor_id_fkey'), 'subject_classes', type_='foreignkey')
    op.create_foreign_key(None, 'subject_classes', 'tenant_members', ['professor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_classes', type_='foreignkey')
    op.create_foreign_key(op.f('subject_classes_professor_id_fkey'), 'subject_classes', 'users', ['professor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
