"""add deleted to tenant_members and partial index

Revision ID: fc71fc6cb340
Revises: 564c102f9694
Create Date: 2026-08-27 17:44:24.452947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc71fc6cb340'
down_revision: Union[str, Sequence[str], None] = '564c102f9694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_members', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('uq_tenant_user'), 'tenant_members', type_='unique')
    op.create_index('uq_active_tenant_user', 'tenant_members', ['tenant_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted IS FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_tenant_user', table_name='tenant_members', postgresql_where=sa.text('deleted IS FALSE'))
    op.create_unique_constraint(op.f('uq_tenant_user'), 'tenant_members', ['tenant_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenant_members', 'deleted')
    # ### end Alembic commands ###
